version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - next-network

  app:
    build: .
    ports:
      - '3001:3000'
    container_name: app
    restart: always
    tty: true
    volumes:
      - .:/home/node/app
    networks:
      - next-network
    command: ['npm', 'run', 'dev']

networks:
  next-network:
    driver: bridge
